version: '3.8'

services:
  todosapi:
    build:
      context: ./TodosApi
      dockerfile: Dockerfile2
    image: todosapi
    ports:
      - "5075:5075"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_FILE: /app/todos.db
    volumes:
      - todos-data:/app

  todoapp:
    build:
      context: ./TodoApp
      dockerfile: Dockerfile1
    image: todoapp
    ports:
      - "5000:80"
    environment:
      API_URL: "http://localhost:5075"

volumes:
  todos-data:
    driver: local
