version: '3.9'


services:
  todosapi:
    build:
      context: .
      dockerfile: ./TodosApi/Dockerfile
    ports:
      - "5075:5075"  # Map API service to port 5075
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Data Source=/app/todos.db"  # Point to the database inside the container
    volumes:
      - ./TodosApi:/app  # Bind mount the entire TodosApi directory, including todos.db, for development

  todoapp:
    build:
      context: .
      dockerfile: ./TodoApp/Dockerfile
    ports:
      - "5000:80"  # Map frontend to port 5000
    environment:
      API_URL: "http://todosapi:5075"  # Backend API URL

  testapi:
    build:
      context: .
      dockerfile: ./TodosApi/Dockerfile
    command: ["dotnet", "test", "/app/TodosApi.Tests/TodosApi.Tests.csproj"]
    depends_on:
      - todosapi

  testapp:
    build:
      context: .
      dockerfile: ./TodoApp/Dockerfile
    command: ["dotnet", "test", "/app/TodoApp.Tests/TodoApp.Tests.csproj"]
    depends_on:
      - todoapp

volumes:
  todos-data:
    driver: local
