version: '3.8'

services:
  todosapi:
    image: todosapi
    build:
      context: .
      dockerfile: ./TodosApi/Dockerfile2
    ports:
      - "5075:5075"  # Backend mapped to port 5075
    environment:
      ASPNETCORE_ENVIRONMENT: Development  # Development mode
      DB_PROVIDER: sqlite  # Specify SQLite as the provider
      DB_FILE: /app/data/todos.db  # Path to the SQLite database file inside the container
    volumes:
      - todos-data:/app/data  # Mount a volume for database persistence

  todoapp:
    image: todoapp
    build:
      context: .
      dockerfile: ./TodoApp/Dockerfile1
    ports:
      - "5000:80"  # Frontend mapped to port 5000
    environment:
      API_URL: "http://localhost:5075"  # Backend API URL

volumes:
  todos-data:
