version: '3.8'

services:
  services:
  todosapi:
    build:
      context: .
      dockerfile: ./TodosApi/Dockerfile2
    image: todosapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./test-results:/app/TestResults
  todoapp:
    build:
      context: ./TodoApp
      dockerfile: Dockerfile1
    image: todoapp
    ports:
      - "5000:80"
    environment:
      API_URL: "http://localhost:5075"

volumes:
  todos-data:
    driver: local
