// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TodosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241204231217_newController")]
    partial class newController
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TodoApp.Classes.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TimeCompleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentDate = new DateTime(2024, 12, 5, 0, 12, 14, 357, DateTimeKind.Local).AddTicks(1620),
                            IsCompleted = false,
                            Title = "Run for 30 min"
                        },
                        new
                        {
                            Id = 2,
                            CurrentDate = new DateTime(2024, 12, 5, 0, 12, 14, 362, DateTimeKind.Local).AddTicks(6469),
                            IsCompleted = false,
                            Title = "Take kids from the school before 4pm"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
