// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodosApi.Data;

#nullable disable

namespace TodosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241211093346_Categories")]
    partial class Categories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TodosApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryDescription = "Practical things which need to be done as first",
                            Name = "Personal",
                            Priority = true
                        },
                        new
                        {
                            Id = 2,
                            CategoryDescription = "Spend time with loved ones",
                            Name = "Family",
                            Priority = false
                        },
                        new
                        {
                            Id = 3,
                            CategoryDescription = "Stay fit and healthy",
                            Name = "Sport",
                            Priority = false
                        },
                        new
                        {
                            Id = 4,
                            CategoryDescription = "Work-related tasks",
                            Name = "Job",
                            Priority = true
                        },
                        new
                        {
                            Id = 5,
                            CategoryDescription = "Groceries and essentials",
                            Name = "Shopping",
                            Priority = false
                        },
                        new
                        {
                            Id = 6,
                            CategoryDescription = "Take care of yourself",
                            Name = "Beauty & Wellness",
                            Priority = false
                        },
                        new
                        {
                            Id = 7,
                            CategoryDescription = "What to do at home",
                            Name = "Home",
                            Priority = false
                        });
                });

            modelBuilder.Entity("TodosApi.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TimeCompleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            CurrentDate = new DateTime(2024, 12, 11, 10, 33, 45, 543, DateTimeKind.Local).AddTicks(381),
                            IsCompleted = false,
                            Title = "Run for 30 min"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CurrentDate = new DateTime(2024, 12, 11, 10, 33, 45, 548, DateTimeKind.Local).AddTicks(4145),
                            IsCompleted = false,
                            Title = "Take kids from the school before 4.20pm"
                        });
                });

            modelBuilder.Entity("TodosApi.Models.TodoItem", b =>
                {
                    b.HasOne("TodosApi.Models.Category", "Category")
                        .WithMany("Todos")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TodosApi.Models.Category", b =>
                {
                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
