// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodosApi.Data;

#nullable disable

namespace TodosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TodoApp.Classes.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TimeCompleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentDate = new DateTime(2024, 12, 10, 10, 48, 10, 582, DateTimeKind.Local).AddTicks(9756),
                            IsCompleted = false,
                            Title = "Run for 30 min"
                        },
                        new
                        {
                            Id = 2,
                            CurrentDate = new DateTime(2024, 12, 10, 10, 48, 10, 588, DateTimeKind.Local).AddTicks(1139),
                            IsCompleted = false,
                            Title = "Take kids from the school before 4pm"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
