name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Backend Service
      - name: Build Backend Service (TodosApi)
        run: docker build -f TodosApi/Dockerfile2 -t todosapi ./TodosApi

      # Build Frontend Service
      - name: Build Frontend Service (TodoApp)
        run: docker build -f TodoApp/Dockerfile1 -t todoapp ./TodoApp


      # Run Backend Tests
      - name: Run Backend Tests
        run: docker run --rm todosapi dotnet test /app/TodosApi.sln --logger:trx

      # Run Frontend Tests
      - name: Run Frontend Tests
        run: docker run --rm todoapp npm run test


      # Tear Down Services
      - name: Tear Down Services
        run: docker compose down
