name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build and Run Tests
      - name: Build and Test Services
        run: |
          docker compose build
          docker compose up test

      # Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-test-results
          path: ./test-results


      # Tear Down Services
      - name: Tear Down Services
        run: docker compose down
