# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Build and Start Services
      run: |
        docker-compose -f docker-compose.yml up --build --abort-on-container-exit
    - name: Run Tests
      run: |
        docker-compose -f docker-compose.yml exec backend dotnet test
    - name: Tear Down
      run: |
        docker-compose -f docker-compose.yml down


 
