name: Build and Test TodoApp and TodosApi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

    

      # Build TodoApp
      - name: Build TodoApp
        run: |
          docker build -f TodoApp/Dockerfile1 -t todoapp ./TodoApp

      # Build TodosApi
      - name: Build TodosApi
        run: |
          docker build -f TodosApi/Dockerfile2 -t todosapi ./TodosApi

      # Start Services
      - name: Start Services
        run: |
          docker compose up -d

      # Run Tests
      - name: Run Tests
        run: |
          docker compose exec todosapi dotnet test
          docker compose exec todoapp npm run test

      # Tear Down Services
      - name: Tear Down Services
        run: docker compose down
